# Generated by Django 4.2.2 on 2023-07-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
